title: Mark Collins Enterprise IT Management MSc.
description: Portfolio of work completed for the MSc in Enterprise IT Management at University of Essex
show_downloads: false
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme 
