title: Mark Collins Enterprise IT Management MSc.
description: [Portfolio of work completed for the MSc in Enterprise IT Management at University of Essex](https://mcollins87.github.io/MSC_EnterpriseIT/)
show_downloads: true
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme 
