title: Mark Collins | MSc Enterprise IT Management

description: >
  Academic e-portfolio for the MSc Enterprise IT Management
  programme at the University of Essex Online.

url: "https://mcollins87.github.io"
baseurl: "/MSC_EnterpriseIT"

markdown: kramdown

exclude:
  - README.md